[build-system]
requires = ["maturin>=1.10,<2.0"]
build-backend = "maturin"

[project]
name = "rubixpy"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.8"
dependencies = ["pygame>=2.6.1"]

[tool.maturin]
features = ["pyo3/extension-module"]
